path: /home/dyd/Vehicle-Identification-and-Detection-Algorithm/model-training/data/

val:
  - highway/images/val
  - nonhighway/images/val
  - generic/images/val

nc: 7
names: ["car", "truck", "bus", "motorcycle", "reboque", "_", "pedestre"]
